ALTER TABLE T_CATERER
DROP COLUMN ADDRESS
ADD dejureaddress NVARCHAR2(150) NOT NULL
ADD defactoaddress NVARCHAR2(150) NOT NULL
ADD email NVARCHAR2(150)

ALTER TABLE T_INPRICE
ADD CONSTRAINT pk_price_material PRIMARY KEY(id_material, price_date)

CREATE TABLE T_GROUP
  (id_group INT NOT NULL,
  name_group NVARCHAR2(150) NOT NULL,
  CONSTRAINT pk_group PRIMARY KEY(id_group) ENABLE)

ALTER TABLE T_MATERIAL
ADD id_group INT
ADD CONSTRAINT fk_material_group FOREIGN KEY(id_group)
REFERENCES t_group(id_group) ON DELETE SET NULL